### ISSUE TITLE
显示FamiliarRecyclerView没有注册

### ISSUE THREAD

**Issue by keliuyue** [iwgang/FamiliarRecyclerView#15]
java.lang.IllegalStateException: Observer cn.iwgang.familiarrecyclerview.FamiliarRecyclerView$2@28908f6c was not registered.
                                                                          at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6049)
                                                                          at cn.iwgang.familiarrecyclerview.FamiliarRecyclerView.onDetachedFromWindow(FamiliarRecyclerView.java:264)
                                                                          at android.view.View.dispatchDetachedFromWindow(View.java:13620)
                                                                          at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2840)
                                                                          at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
                                                                          at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
                                                                          at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4233)
                                                                          at android.view.ViewGroup.removeViewAt(ViewGroup.java:4182)
                                                                          at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:664)
                                                                          at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:7150)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:7422)
                                                                          at android.support.v7.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1231)
                                                                          at android.support.v7.widget.LinearLayoutManager.recycleViewsFromStart(LinearLayoutManager.java:1277)
                                                                          at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1347)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1371)
                                                                          at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
                                                                          at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
                                                                          at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4413)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:612)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:580)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5669)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by iwgang** [comment]
请帖一下代码，另外，可以参考一下 [Demo](https://github.com/iwgang/FamiliarRecyclerView/blob/master/app/src/main/java/cn/iwgang/familiarrecyclerviewdemo/LinearLayoutActivity.java) 中的代码先

**Comment by keliuyue** [comment]
package com.leo.ke.lingyongdai.fragment.youhuiquan;

import android.graphics.Color;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import com.leo.ke.lingyongdai.R;
import com.leo.ke.lingyongdai.adapter.YouhuiquanRecyclerAdapter;
import com.leo.ke.lingyongdai.base.BaseFragment;
import com.leo.ke.lingyongdai.view.LoadView;

import java.util.ArrayList;
import java.util.List;

import butterknife.BindView;
import butterknife.ButterKnife;
import cn.iwgang.familiarrecyclerview.FamiliarRecyclerView;
import cn.iwgang.familiarrecyclerview.FamiliarRefreshRecyclerView;

public class WeibangdingFragment extends BaseFragment {

```
@BindView(R.id.refreshRecyclerView_weibangding)
FamiliarRefreshRecyclerView refreshRecyclerView;
private YouhuiquanRecyclerAdapter adapter;

private List<String> data;
private FamiliarRecyclerView recyclerView;


@Override
protected int getLayoutId() {
    return R.layout.fragment_weibangding;
}

@Override
protected void initView(View view, Bundle savedInstanceState) {
    initList();
    initRecycler();
}

private void initRecycler() {
    // 添加头部
```

//        View headerView = LayoutInflater.from(getActivity()).inflate(R.layout.header_huankuan_plan,null);
//        recyclerView = refreshRecyclerView.getFamiliarRecyclerView();
//        recyclerView.addHeaderView(headerView);

```
    // 设置上拉和下拉
    adapter = new YouhuiquanRecyclerAdapter(data,getActivity());
    refreshRecyclerView.setAdapter(adapter);
    refreshRecyclerView.setLoadMoreView(new LoadView(getActivity()));
    refreshRecyclerView.setLoadMoreEnabled(true);
    refreshRecyclerView.setPullRefreshEnabled(true);
    refreshRecyclerView.setColorSchemeColors(0xFFFF5000, Color.RED, Color.YELLOW, Color.GREEN);

    refreshRecyclerView.setOnItemClickListener(new FamiliarRecyclerView.OnItemClickListener() {
        @Override
        public void onItemClick(FamiliarRecyclerView familiarRecyclerView, View view, int position) {
            Toast.makeText(getActivity(), "click"+position, Toast.LENGTH_SHORT).show();
        }
    });
    // 加载更多
    refreshRecyclerView.setOnLoadMoreListener(new FamiliarRefreshRecyclerView.OnLoadMoreListener() {
        @Override
        public void onLoadMore() {
            new android.os.Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    refreshRecyclerView.loadMoreComplete();
                }
            }, 1000);
        }
    });

    // 下拉
    refreshRecyclerView.setOnPullRefreshListener(new FamiliarRefreshRecyclerView.OnPullRefreshListener() {
        @Override
        public void onPullRefresh() {
            new android.os.Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    refreshRecyclerView.pullRefreshComplete();
                    Log.i("leo", "加载完成啦...");
                }
            }, 1000);
        }
    });
}

private void initList() {
    data = new ArrayList<>();
    for (int i = 0; i < 10; i++) {
        data.add("5元优惠券");
    }
}

@Override
protected void registerListener() {

}

@Override
protected void initData() {

}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    // TODO: inflate a fragment view
    View rootView = super.onCreateView(inflater, container, savedInstanceState);
    ButterKnife.bind(this, rootView);
    return rootView;
}
```

}

**Comment by iwgang** [comment]
先跑一下Demo吧，对比看下布局文件

**Comment by keliuyue** [comment]
Demo没问题，但是我这跑就是出现没注册还有一个Make true if has the same id。

**Comment by iwgang** [comment]
不应该的，仔细比对一下
另外，有个别方法有调用顺序之分

**Comment by keliuyue** [comment]
好的，我再试试。

**Comment by iwgang** [comment]
好的，如果可以也请反馈下问题原因，谢谢了

如果还是不行，能否整理一个 demo 给我？
