### ISSUE TITLE
Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_food_list. Make sure other views do not use the same id.

### ISSUE THREAD

**Issue by ghost** [iwgang/FamiliarRecyclerView#25]
I used it on activity.
If I run intent of Alipay, app is crashed by this issue.

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kyad.yuisu/com.kyad.yuisu.view.activity.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_food_list. Make sure other views do not use the same id.
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5383)
                                                                    at android.app.ActivityThread.access$1200(ActivityThread.java:221)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1800)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                 Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_food_list. Make sure other views do not use the same id.
                                                                    at android.view.View.onRestoreInstanceState(View.java:16062)
                                                                    at android.view.View.dispatchRestoreInstanceState(View.java:16037)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3430)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                    at android.view.View.restoreHierarchyState(View.java:16015)
                                                                    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2314)
                                                                    at android.app.Activity.onRestoreInstanceState(Activity.java:1164)
                                                                    at android.app.Activity.performRestoreInstanceState(Activity.java:1109)
                                                                    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1191)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3226)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5383) 
                                                                    at android.app.ActivityThread.access$1200(ActivityThread.java:221) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1800) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:158) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `

I hope you resolve it.

**Comment by starman1108** [comment]
check your gradle version.
use this.

`compile 'com.github.iwgang:familiarrecyclerview:1.3.3'`

**Comment by happymario** [comment]
Thank you.

**Comment by ghost** [comment]
Yes. I used 1.3.2. thank you.

**Comment by MissMyDearBear** [comment]
这个是什么原因呢？

**Comment by mwshubham** [comment]
What was the issue just curious
