### ISSUE TITLE
滑动到底崩溃

### ISSUE THREAD

**Issue by wyy283** [iwgang/FamiliarRecyclerView#4]
当滑动到底部正在加载中时，连续快速往上拉回导致崩溃，下面是崩溃日志
 Process: cn.iwgang.familiarrecyclerviewdemo, PID: 17226
    java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:1
            at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6246)
            at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6212)
            at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6200)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
            at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
            at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
            at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3807)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:543)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5094)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by iwgang** [comment]
谢谢反馈

这应该不算是个bug, 只是当时写demo时偷懒没有做这些容错处理
因为正常使用时, 加载更多时应该判断当前是否有正在加载

这个库的初衷不是为了做下拉刷新和加载更多, 只是提供一些额外定制化的功能, 好让其它扩展实现起来更方便

**Comment by wyy283** [comment]
你说的 “加载更多时应该判断当前是否有正在加载”，   我不是很明白，您能告诉我具体原因及解决方案吗？

**Comment by iwgang** [comment]
比如有个布尔值, isLoadingMore
当滚动到底部, 开始加载数据时, 把这个值设置成true,  并在滚动到底部监听中判断, 如果isLoadingMore=true就不往下执行,  然后当加载完更多数据并显示完后, 又把isLoadingMore设置成false

**Comment by wyy283** [comment]
我刚刚就是按你这样做的，但是并没有解决。下面是我在你demo的基础上改的。
 new android.os.Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        if(!isRefreshing){
                            isRefreshing=true;
                            System.out.println("loading");
                            int startPos = mDatas.size() - 1;
                            List<String> newDatas = getDatas();
                            mDatas.addAll(newDatas);
                            mAdapter.notifyItemRangeChanged(startPos, newDatas.size());
                            isRefreshing=false;
                        }

```
                    mPbLoadMoreProgressBar.setVisibility(View.GONE);
                    mTvLoadMoreText.setText("松开加载更多");

                    if (mDatas.size() >= 50) {
                        mRecyclerView.removeFooterView(mFooterLoadMoreView);
                    }
                }
            }, 3000);
```

**Comment by iwgang** [comment]
确实这样也不行, 我再看看
