### ISSUE TITLE
动态更改数据，滑动报错

### ISSUE THREAD

**Issue by Kenmmm** [iwgang/FamiliarRecyclerView#6]
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList android.support.v7.widget.StaggeredGridLayoutManager$Span.mViews' on a null object reference
                                                                      at android.support.v7.widget.StaggeredGridLayoutManager$Span.access$300(StaggeredGridLayoutManager.java:2094)
                                                                      at android.support.v7.widget.StaggeredGridLayoutManager.recycleFromStart(StaggeredGridLayoutManager.java:1731)
                                                                      at android.support.v7.widget.StaggeredGridLayoutManager.recycle(StaggeredGridLayoutManager.java:1595)
                                                                      at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1518)
                                                                      at android.support.v7.widget.StaggeredGridLayoutManager.scrollBy(StaggeredGridLayoutManager.java:1926)
                                                                      at android.support.v7.widget.StaggeredGridLayoutManager.scrollVerticallyBy(StaggeredGridLayoutManager.java:1846)
                                                                      at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1492)
                                                                      at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2416)
                                                                      at android.view.View.dispatchTouchEvent(View.java:9294)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                      at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                      at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                      at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                      at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                      at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
                                                                      at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                    at android.vi

**Comment by iwgang** [comment]
@ThinkWYP 能否提供一下具体场景或者相关动态更改数据的代码？

**Comment by Kenmmm** [comment]
Observer cn.iwgang.familiarrecyclerview.FamiliarRecyclerView$2@a17b8a3 is already registered.这个错是？

**Comment by iwgang** [comment]
@ThinkWYP  能否提供一下测试代码？

**Comment by Kenmmm** [comment]
getInfo();  
TagDetailAdapter mTagAdapter = new TagDetailAdapter(mRecycler, mData, R.layout.infos_list);
mRecycler.setAdapter(mTagAdapter);

public void getInfo(){
  AsyncHttpClient.get(URLConfig.tag_detail, map, new BaseAHRHandler() {
            @Override
            public void onSuccess(String data) throws Exception {
                TagDetailEntity detailEntity = gson.fromJson(data, TagDetailEntity.class);
                if (detailEntity.data == null && detailEntity.data.feeds.size() == 0) {
                    return;
                }
                mData.clear();
                mData.addAll(detailEntity.data.feeds);
                int pos = mData.size();
                mTagAdapter.notifyItemInserted(pos);
            }
}

现在场景就是筛选，点一个按钮获取一次数据，然后更新adapter，现在这样没有任何效果

**Comment by iwgang** [comment]
@ThinkWYP 数据已经清空了，把mTagAdapter.notifyItemInserted(pos);
 改成mTagAdapter.notifyDataSetChanged()吧

**Comment by Kenmmm** [comment]
只要是通知数据变化的我都试过。。。可能是我写的问题

**Comment by iwgang** [comment]
你看一下独立一个Demo程序，测评一下有没问题，如果还有问题，把Demo发下我邮箱iwgang@163.com，谢谢了

**Comment by BennyTian** [comment]
所以 这个问题最后解决了么 ? @AndrWang
