### ISSUE TITLE
setEmptyView(mEmptyView, true)之后,setAdapter(adapter)就会空指针,如果不传true,则不抱错,但是空数据的时候不显示mEmptyView

### ISSUE THREAD

**Issue by LarryLGHao** [iwgang/FamiliarRecyclerView#8]
java.lang.NullPointerException
                                           at cn.iwgang.familiarrecyclerview.FamiliarRecyclerView.setAdapter(FamiliarRecyclerView.java:213)
                                           at com.liuliuyxq.android.activities.FansOrAttentionActivity$1.success(FansOrAttentionActivity.java:138)
                                           at com.liuliuyxq.android.activities.FansOrAttentionActivity$1.success(FansOrAttentionActivity.java:115)
                                           at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
                                           at android.os.Handler.handleCallback(Handler.java:733)
                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                           at android.os.Looper.loop(Looper.java:136)
                                           at android.app.ActivityThread.main(ActivityThread.java:5001)
                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by iwgang** [comment]
你好，可以提供一下代码吗？

**Comment by iwgang** [comment]
知道什么原因了，你的emptyView没有和RecyclerView放在一个布局中吧？   

设置setEmptyView(view, true)  可以不放layout.xml中， 但setEmptyView(view)中的view必需和RecyclerView放在同一个布局中

具体原因完全同ListView
